// <auto-generated />
namespace MVP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initialised32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialised32));
        
        string IMigrationMetadata.Id
        {
            get { return "201711282115071_Initialised3.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
